package com.example.springbootquartz.model;

import java.util.Date;

public class OrderStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.id
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.order_count
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private Integer orderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.create_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.create_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.update_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_statistics.update_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.id
     *
     * @return the value of t_order_statistics.id
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.id
     *
     * @param id the value for t_order_statistics.id
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.time
     *
     * @return the value of t_order_statistics.time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.time
     *
     * @param time the value for t_order_statistics.time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.order_count
     *
     * @return the value of t_order_statistics.order_count
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.order_count
     *
     * @param orderCount the value for t_order_statistics.order_count
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.create_user
     *
     * @return the value of t_order_statistics.create_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.create_user
     *
     * @param createUser the value for t_order_statistics.create_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.create_time
     *
     * @return the value of t_order_statistics.create_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.create_time
     *
     * @param createTime the value for t_order_statistics.create_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.update_user
     *
     * @return the value of t_order_statistics.update_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.update_user
     *
     * @param updateUser the value for t_order_statistics.update_user
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_statistics.update_time
     *
     * @return the value of t_order_statistics.update_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_statistics.update_time
     *
     * @param updateTime the value for t_order_statistics.update_time
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}