package com.example.springbootquartz.dao;

import com.example.springbootquartz.model.OrderStatistics;
import com.example.springbootquartz.model.OrderStatisticsExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    long countByExample(OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int deleteByExample(OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int insert(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int insertSelective(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    List<OrderStatistics> selectByExample(OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    OrderStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderStatistics record, @Param("example") OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int updateByExample(@Param("record") OrderStatistics record, @Param("example") OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int updateByPrimaryKeySelective(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_statistics
     *
     * @mbg.generated Mon May 06 22:53:32 CST 2019
     */
    int updateByPrimaryKey(OrderStatistics record);
}